<?xml version="1.0" encoding="UTF-8"?>
<alr:test-suite xmlns:alr="urn:model.allure.qatools.yandex.ru" start="1729890460762" stop="1729890460822" version="1.4.0">
  <name>Magento\Framework\Validator\Test\Unit\Constraint\Option\CallbackTest</name>
  <test-cases>
    <test-case start="1729890460767" stop="1729890460767" status="passed">
      <name>testGetValue with data set #0</name>
    </test-case>
    <test-case start="1729890460768" stop="1729890460775" status="passed">
      <name>testGetValue with data set #1</name>
    </test-case>
    <test-case start="1729890460775" stop="1729890460776" status="passed">
      <name>testGetValue with data set #2</name>
    </test-case>
    <test-case start="1729890460781" stop="1729890460785" status="passed">
      <name>testGetValue with data set #3</name>
    </test-case>
    <test-case start="1729890460786" stop="1729890460787" status="passed">
      <name>testGetValue with data set #4</name>
    </test-case>
    <test-case start="1729890460791" stop="1729890460791" status="canceled">
      <name>testSetArguments with data set #0</name>
      <failure>
        <message>Skipped in #27500 due to testing protected/private methods and properties</message>
        <stack-trace>#0 /home/adrian-skowronski/www/mint/vendor/magento/framework/Validator/Test/Unit/Constraint/Option/CallbackTest.php(108): PHPUnit\Framework\Assert::markTestSkipped()
#1 /home/adrian-skowronski/www/mint/vendor/phpunit/phpunit/src/Framework/TestCase.php(1548): Magento\Framework\Validator\Test\Unit\Constraint\Option\CallbackTest-&gt;testSetArguments()
#2 /home/adrian-skowronski/www/mint/vendor/phpunit/phpunit/src/Framework/TestCase.php(1154): PHPUnit\Framework\TestCase-&gt;runTest()
#3 /home/adrian-skowronski/www/mint/vendor/phpunit/phpunit/src/Framework/TestResult.php(728): PHPUnit\Framework\TestCase-&gt;runBare()
#4 /home/adrian-skowronski/www/mint/vendor/phpunit/phpunit/src/Framework/TestCase.php(904): PHPUnit\Framework\TestResult-&gt;run()
#5 /home/adrian-skowronski/www/mint/vendor/phpunit/phpunit/src/Framework/TestSuite.php(675): PHPUnit\Framework\TestCase-&gt;run()
#6 /home/adrian-skowronski/www/mint/vendor/phpunit/phpunit/src/Framework/TestSuite.php(675): PHPUnit\Framework\TestSuite-&gt;run()
#7 /home/adrian-skowronski/www/mint/vendor/phpunit/phpunit/src/Framework/TestSuite.php(675): PHPUnit\Framework\TestSuite-&gt;run()
#8 /home/adrian-skowronski/www/mint/vendor/phpunit/phpunit/src/Framework/TestSuite.php(675): PHPUnit\Framework\TestSuite-&gt;run()
#9 /home/adrian-skowronski/www/mint/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(653): PHPUnit\Framework\TestSuite-&gt;run()
#10 /home/adrian-skowronski/www/mint/vendor/phpunit/phpunit/src/TextUI/Command.php(144): PHPUnit\TextUI\TestRunner-&gt;run()
#11 /home/adrian-skowronski/www/mint/vendor/phpunit/phpunit/src/TextUI/Command.php(97): PHPUnit\TextUI\Command-&gt;run()
#12 /home/adrian-skowronski/www/mint/vendor/phpunit/phpunit/phpunit(98): PHPUnit\TextUI\Command::main()
#13 {main}</stack-trace>
      </failure>
    </test-case>
    <test-case start="1729890460797" stop="1729890460797" status="canceled">
      <name>testSetArguments with data set #1</name>
      <failure>
        <message>Skipped in #27500 due to testing protected/private methods and properties</message>
        <stack-trace>#0 /home/adrian-skowronski/www/mint/vendor/magento/framework/Validator/Test/Unit/Constraint/Option/CallbackTest.php(108): PHPUnit\Framework\Assert::markTestSkipped()
#1 /home/adrian-skowronski/www/mint/vendor/phpunit/phpunit/src/Framework/TestCase.php(1548): Magento\Framework\Validator\Test\Unit\Constraint\Option\CallbackTest-&gt;testSetArguments()
#2 /home/adrian-skowronski/www/mint/vendor/phpunit/phpunit/src/Framework/TestCase.php(1154): PHPUnit\Framework\TestCase-&gt;runTest()
#3 /home/adrian-skowronski/www/mint/vendor/phpunit/phpunit/src/Framework/TestResult.php(728): PHPUnit\Framework\TestCase-&gt;runBare()
#4 /home/adrian-skowronski/www/mint/vendor/phpunit/phpunit/src/Framework/TestCase.php(904): PHPUnit\Framework\TestResult-&gt;run()
#5 /home/adrian-skowronski/www/mint/vendor/phpunit/phpunit/src/Framework/TestSuite.php(675): PHPUnit\Framework\TestCase-&gt;run()
#6 /home/adrian-skowronski/www/mint/vendor/phpunit/phpunit/src/Framework/TestSuite.php(675): PHPUnit\Framework\TestSuite-&gt;run()
#7 /home/adrian-skowronski/www/mint/vendor/phpunit/phpunit/src/Framework/TestSuite.php(675): PHPUnit\Framework\TestSuite-&gt;run()
#8 /home/adrian-skowronski/www/mint/vendor/phpunit/phpunit/src/Framework/TestSuite.php(675): PHPUnit\Framework\TestSuite-&gt;run()
#9 /home/adrian-skowronski/www/mint/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(653): PHPUnit\Framework\TestSuite-&gt;run()
#10 /home/adrian-skowronski/www/mint/vendor/phpunit/phpunit/src/TextUI/Command.php(144): PHPUnit\TextUI\TestRunner-&gt;run()
#11 /home/adrian-skowronski/www/mint/vendor/phpunit/phpunit/src/TextUI/Command.php(97): PHPUnit\TextUI\Command-&gt;run()
#12 /home/adrian-skowronski/www/mint/vendor/phpunit/phpunit/phpunit(98): PHPUnit\TextUI\Command::main()
#13 {main}</stack-trace>
      </failure>
    </test-case>
    <test-case start="1729890460803" stop="1729890460805" status="passed">
      <name>testGetValueException with data set #0</name>
    </test-case>
    <test-case start="1729890460806" stop="1729890460807" status="passed">
      <name>testGetValueException with data set #1</name>
    </test-case>
    <test-case start="1729890460808" stop="1729890460810" status="passed">
      <name>testGetValueException with data set #2</name>
    </test-case>
    <test-case start="1729890460811" stop="1729890460812" status="passed">
      <name>testGetValueException with data set #3</name>
    </test-case>
    <test-case start="1729890460814" stop="1729890460815" status="passed">
      <name>testGetValueException with data set #4</name>
    </test-case>
    <test-case start="1729890460815" stop="1729890460821" status="passed">
      <name>testGetValueException with data set #5</name>
    </test-case>
  </test-cases>
</alr:test-suite>
